# Generated by Django 2.2.14 on 2021-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlDispose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32)),
                ('port', models.CharField(max_length=8)),
                ('user', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('dbName', models.CharField(max_length=16)),
                ('sqlType', models.CharField(max_length=8)),
                ('mark', models.CharField(max_length=8)),
                ('encoding', models.CharField(max_length=8)),
                ('linkTest', models.SmallIntegerField(default=0, max_length=1)),
                ('founder', models.CharField(max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_person', models.CharField(max_length=8)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ext1', models.CharField(max_length=128)),
                ('ext2', models.CharField(max_length=128)),
                ('ext3', models.CharField(max_length=128)),
                ('ext4', models.CharField(max_length=128)),
                ('ext5', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-update_time', '-create_time'],
            },
        ),
    ]
