# Generated by Django 2.2.14 on 2021-05-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlDispose', '0005_auto_20210509_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldispose',
            name='create_time',
            field=models.DateTimeField(blank=True, default='2021-05-10 21:48:55', null=True),
        ),
    ]
