# Generated by Django 2.2.14 on 2021-05-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlDispose', '0008_sqldispose_is_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqldispose',
            name='mark',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
