USER_EXIST = 1000
USER_EXIST_MSG = '该用户已存在'
REGISTER_ERROR = 1001
REGISTER_ERROR_MSG = '密码不一致，请重新输入密码'
LOGIN_ERROR = 1002
LOGIN_ERROR_MSG = '请登录'
LOGIN_VERIFY = 1003
LOGIN_VERIFY_MSG = '用户或密码错误'

INSERT_SQL_FAIL = 2000
INSERT_SQL_FAIL_MSG = '引用标识已存在，新增失败'
