# Generated by Django 2.2.14 on 2021-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=8, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('is_del', models.SmallIntegerField(default='0')),
                ('ext1', models.CharField(max_length=128)),
                ('ext2', models.CharField(max_length=128)),
                ('ext3', models.CharField(max_length=128)),
                ('ext4', models.CharField(max_length=128)),
                ('ext5', models.CharField(max_length=128)),
            ],
        ),
    ]
